Grupo de Preparação de Dados

##Autor

Thyago Alexandre Pinheiro

#Transformação de dados

A transformação de dados é uma etapa fundamental na preparação de dados, que envolve a aplicação de técnicas e métodos para preparar e manipular os dados brutos, tornando-os adequados para análise e modelagem. A importância da transformação de dados reside no fato de que os dados coletados do mundo real muitas vezes apresentam complexidades, irregularidades e peculiaridades que podem dificultar a análise direta ou prejudicar a eficácia dos algoritmos de aprendizado de máquina.

Algumas técnicas:

1.   Tratamento de Valores Ausentes: Muitos conjuntos de dados reais contêm valores ausentes, que podem afetar a qualidade dos resultados de análise e modelagem. A transformação de dados inclui técnicas para tratar esses valores ausentes de maneira adequada, como preenchimento com média, mediana ou outros métodos de imputação.


2.   Padronização e Normalização: Ao transformar os dados para uma escala comum, como a padronização ou normalização, é possível evitar que certos atributos dominem os outros durante a análise e modelagem. Isso é especialmente importante em algoritmos sensíveis à escala, como regressão linear.

3.   Criação de Novas Variáveis (Feature Engineering): A transformação de dados permite a criação de novas variáveis com base nas informações existentes. Essas novas variáveis podem conter informações mais relevantes ou fornecer insights adicionais para análise e modelagem.

Entre outras.

In [ ]:
# Importando o pandas
import pandas as pd

In [ ]:
# Importando os dados
dados = pd.read_csv('/content/winequalityN.csv')

Sobre o conjunto:

Nome: Qualidade de vinhos

https://www.kaggle.com/datasets/rajyellow46/wine-quality

Variáveis ​​de entrada (com base em testes físico-químicos):

1 - acidez fixa

2 - acidez volátil

3 - ácido cítrico

4 - açúcar residual

5 - cloretos

6 - dióxido de enxofre livre

7 - dióxido de enxofre total

8 - densidade

9 - pH

10 - sulfatos

11 - álcool

Variável de saída (com base em dados sensoriais):

12 - qualidade (pontuação entre 0 e 10)

In [ ]:
# Visualizando a tabela
dados

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [ ]:
# Podemos visualizar as informações estatísticas
dados.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,6487.000000,6489.000000,6494.000000,6495.000000,6495.000000,6497.000000,6497.000000,6497.000000,6488.000000,6493.000000,6497.000000,6497.000000
mean,7.216579,0.339691,0.318722,5.444326,0.056042,30.525319,115.744574,0.994697,3.218395,0.531215,10.491801,5.818378
std,1.296750,0.164649,0.145265,4.758125,0.035036,17.749400,56.521855,0.002999,0.160748,0.148814,1.192712,0.873255
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992340,3.110000,0.430000,9.500000,5.000000
50%,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,6.000000
75%,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.996990,3.320000,0.600000,11.300000,6.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   type                  6497 non-null   object
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB

In [ ]:
# Verificar se há valores ausentes
dados.isnull().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [ ]:
# Calcular a média de cada coluna
medias = dados.mean()

# Preencher os valores ausentes com a média de cada coluna
dados.fillna(medias, inplace=True)

No código acima, medias é uma série que contém a média de cada coluna do DataFrame. O método fillna() preenche os valores ausentes no DataFrame com os respectivos valores de média calculados para cada coluna.

Isso irá substituir os valores ausentes pelo valor médio de cada coluna.

In [ ]:
# Verificar se há duplicatas
dados.duplicated().sum()

1168

In [ ]:
# Remover duplicatas
dados = dados.drop_duplicates()

##Padronização

É o redimensionamento dos recursos para criar um “padrão” garantindo que os novos dados tenham média zero e desvio padrão igual a 1

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler

In [ ]:
# Importando o StandardScaler

from sklearn.preprocessing import StandardScaler

In [ ]:
# Selecionar apenas as colunas numéricas para padronização
colunas_numericas = dados.select_dtypes(include=[float, int]).columns
# selecionamos apenas as colunas numéricas usando select_dtypes

# Criar um objeto de padronização
scaler = StandardScaler()

# Padronizar os dados
dados[colunas_numericas] = scaler.fit_transform(dados[colunas_numericas])

dados

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,-0.165087,-0.440021,0.280208,3.477382,-0.316815,0.838865,0.984149,2.177419,-1.401186,-0.555267,-1.475154,0.231800
1,white,-0.695163,-0.261684,0.144245,-0.766859,-0.208407,-0.900220,0.314921,-0.180598,0.472180,-0.288309,-0.885144,0.231800
2,white,0.667890,-0.380575,0.552136,0.410863,-0.181305,-0.002628,-0.301474,0.189947,0.222398,-0.622007,-0.379421,0.231800
3,white,-0.013636,-0.677803,0.008281,0.766401,0.035512,0.951064,1.265929,0.358377,-0.214721,-0.888964,-0.547996,0.231800
6,white,-0.770888,-0.142793,-1.079428,0.433084,-0.316815,-0.002628,0.385366,0.122576,-0.277166,-0.421788,-0.800857,0.231800
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6490,red,-0.695163,0.986673,-1.283374,-0.611310,0.523349,-0.058727,-1.305316,0.405538,1.221527,1.446916,0.379162,0.231800
6491,red,-0.316537,1.640575,-1.623283,-0.700195,0.306532,-0.114827,-1.340539,0.664919,1.221527,1.914092,-0.885144,0.231800
6492,red,-0.770888,1.521684,-1.623283,-0.677974,0.902778,0.109572,-1.234871,0.122576,1.408863,0.312346,-0.042273,-0.904665
6495,red,-0.998063,1.789189,-1.351356,-0.677974,0.496247,0.109572,-1.234871,0.314585,2.158210,1.179958,-0.295134,-0.904665
6496,red,-0.922338,-0.202239,1.028009,-0.322435,0.279430,-0.675822,-1.270093,0.321323,1.034190,0.846261,0.379162,0.231800

Após a execução, as colunas numéricas do DataFrame estarão padronizadas, ou seja, terão média zero e desvio padrão igual a um, o que é útil para muitos algoritmos de aprendizado de máquina que podem se beneficiar da mesma escala entre os atributos.

##Normalização

Uma alternativa a padronização é normalizar os dados entre um valor mínimo e máximo (geralmente entre 0 e 1)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
# Selecionar apenas as colunas numéricas para normalização
colunas_numericas = dados.select_dtypes(include=[float, int]).columns

# Criar um objeto de normalização
scaler = MinMaxScaler()

# Normalizar os dados
dados[colunas_numericas] = scaler.fit_transform(dados[colunas_numericas])

dados

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,0.264463,0.126667,0.216867,0.308282,0.059801,0.152778,0.377880,0.267785,0.217054,0.129213,0.115942,0.500000
1,white,0.206612,0.146667,0.204819,0.015337,0.066445,0.045139,0.290323,0.132832,0.449612,0.151685,0.217391,0.500000
2,white,0.355372,0.133333,0.240964,0.096626,0.068106,0.100694,0.209677,0.154039,0.418605,0.123596,0.304348,0.500000
3,white,0.280992,0.100000,0.192771,0.121166,0.081395,0.159722,0.414747,0.163678,0.364341,0.101124,0.275362,0.500000
6,white,0.198347,0.160000,0.096386,0.098160,0.059801,0.100694,0.299539,0.150183,0.356589,0.140449,0.231884,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6490,red,0.206612,0.286667,0.078313,0.026074,0.111296,0.097222,0.078341,0.166377,0.542636,0.297753,0.434783,0.500000
6491,red,0.247934,0.360000,0.048193,0.019939,0.098007,0.093750,0.073733,0.181222,0.542636,0.337079,0.217391,0.500000
6492,red,0.198347,0.346667,0.048193,0.021472,0.134551,0.107639,0.087558,0.150183,0.565891,0.202247,0.362319,0.333333
6495,red,0.173554,0.376667,0.072289,0.021472,0.109635,0.107639,0.087558,0.161172,0.658915,0.275281,0.318841,0.333333
6496,red,0.181818,0.153333,0.283133,0.046012,0.096346,0.059028,0.082949,0.161558,0.519380,0.247191,0.434783,0.500000

Após a execução, as colunas numéricas do DataFrame estarão normalizadas, ou seja, seus valores estarão no intervalo [0, 1], com base no mínimo e máximo de cada coluna.

###Normalizando dados dispersos

In [ ]:
from sklearn.preprocessing import MaxAbsScaler

O MaxAbsScaler funciona de uma maneira semelhante, porém dividindo todos os dados pelo máximo absoluto daquela coluna.

Isso faz com que o range seja de -1 a 1 caso existam valores negativos, funciona muito bem para trabalhar com dados dispersos / espalhados.

In [ ]:
# Selecionar apenas as colunas numéricas para normalização
colunas_numericas = dados.select_dtypes(include=[float, int]).columns

# Criar um objeto de normalização para dados dispersos
scaler = MaxAbsScaler()

# Normalizar os dados dispersos
dados[colunas_numericas] = scaler.fit_transform(dados[colunas_numericas])

dados

###Normalizando dados com outliers

Se os dados tiverem muitos outliers, utilizar os métodos mostrados anteriormente pode não funcionar tão bem, isso porque os outliers vão ter dados iguais a 1 e os demais dados vão ficar muito próximos de zero. Como alternativa podemos utilizar o RobustScaler

In [ ]:
from sklearn.preprocessing import RobustScaler

In [ ]:
# Selecionar apenas as colunas numéricas para normalização
colunas_numericas = dados.select_dtypes(include=[float, int]).columns

# Criar um objeto de normalização robusta
scaler = RobustScaler()

# Normalizar os dados com outliers
dados[colunas_numericas] = scaler.fit_transform(dados[colunas_numericas])

dados

O RobustScaler é uma técnica robusta, que utiliza a mediana e o intervalo interquartil (IQR) para dimensionar os dados, tornando-a menos sensível aos outliers. Assim, os valores são normalizados considerando a dispersão dos dados em torno da mediana, o que ajuda a evitar que os outliers distorçam a escala.

Essa abordagem é especialmente útil quando você tem dados que contenham muitos outliers ou quando a distribuição dos dados é altamente assimétrica.

##Discretização

A discretização é o processo de transformar valores contínuos em valores discretos ou categorias. Vamos prosseguir com a discretização dos dados do conjunto "Wine Quality" usando a biblioteca Scikit-learn e a técnica KBinsDiscretizer.

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer

# Selecionar apenas as colunas numéricas para discretização
colunas_numericas = dados.select_dtypes(include=[float, int]).columns

# Definir o número de intervalos desejados
n_bins = 5

# Criar um objeto de discretização
discretizer = KBinsDiscretizer(n_bins=n_bins, encode='ordinal', strategy='uniform')

# Discretizar os dados
dados[colunas_numericas] = discretizer.fit_transform(dados[colunas_numericas])

dados

O KBinsDiscretizer divide os valores contínuos em "n_bins" intervalos discretos, onde "n_bins" é o número de intervalos que você deseja criar para cada coluna numérica.

O parâmetro encode='ordinal' especifica que as categorias serão codificadas como números inteiros, e o parâmetro strategy='uniform' indica que os intervalos serão criados com largura uniforme.

Depois de discretizar os dados, os valores em cada coluna numérica serão substituídos pelos intervalos discretos correspondentes.

##Binarização de variáveis

A binarização é o processo de transformar valores numéricos em valores binários (0 ou 1) com base em um limiar específico. Vamos prosseguir com a binarização das variáveis do conjunto "Wine Quality" usando a técnica Binarizer.

In [ ]:
from sklearn.preprocessing import Binarizer

# Selecionar apenas as colunas numéricas para binarização
colunas_numericas = dados.select_dtypes(include=[float, int]).columns

# Definir o limiar para a binarização
threshold = 5.0

# Criar um objeto de binarização
binarizer = Binarizer(threshold=threshold)

# Binarizar as variáveis
dados[colunas_numericas] = binarizer.fit_transform(dados[colunas_numericas])

dados.head(100)

O Binarizer transforma os valores em 0 ou 1 com base no limiar definido. Valores maiores que o limiar são transformados em 1, enquanto valores iguais ou menores que o limiar são transformados em 0.

No código acima, definimos o limiar como 5.0. Portanto, todos os valores maiores que 5.0 em cada coluna numérica serão binarizados para 1 e todos os valores iguais ou menores que 5.0 serão binarizados para 0.

A binarização é útil quando você deseja transformar valores contínuos em variáveis binárias ou quando deseja trabalhar com modelos que requerem entradas binárias.

Lembre-se de que a binarização pode levar à perda de informações, pois os valores contínuos são transformados em apenas duas categorias (0 ou 1). Portanto, é importante considerar cuidadosamente se a binarização é apropriada para o seu problema específico.

##Feature engineering (Criação de novas variáveis a partir das existentes)

A feature engineering envolve a criação de novas variáveis com base nas informações disponíveis no conjunto de dados existente. Vamos prosseguir com uma simples feature engineering no conjunto "Wine Quality", criando uma nova coluna que indica se o vinho é tinto ou branco com base na coluna "type".

In [ ]:
# Criar uma nova coluna "is_red" indicando se o vinho é tinto (1) ou branco (0)
dados['is_red'] = dados['type'].map({'red': 1, 'white': 0})

dados

A coluna "type" original contém os valores "red" e "white" para indicar se o vinho é tinto ou branco, respectivamente. Através da feature engineering, criamos uma nova coluna chamada "is_red" que terá o valor 1 para vinhos tintos e 0 para vinhos brancos.

Essa nova coluna "is_red" pode ser útil para a análise de dados e também pode ser usada como uma variável de entrada em modelos de aprendizado de máquina.

Além disso, a feature engineering pode envolver diversas outras transformações, como combinação de variáveis existentes, criação de variáveis categóricas a partir de variáveis contínuas, criação de variáveis polinomiais ou interações entre variáveis, entre outras técnicas.

###Conclusão

Em resumo, a transformação de dados é uma etapa crítica na preparação dos dados para análise e modelagem em ciência de dados. Ela permite melhorar a qualidade dos dados, facilitar a detecção de padrões, melhorar o desempenho dos algoritmos de aprendizado de máquina e fornecer insights mais significativos e úteis para a tomada de decisões em diversas áreas, como negócios, saúde, finanças, entre outras.

Referências

Site: https://www.hashtagtreinamentos.com/padronizacao-e-normalizacao-em-ciencia-de-dados

Livro: Python Para Análise de Dados: Tratamento de Dados com Pandas, NumPy e IPython por Wes McKinney.

Artigo: https://medium.com/epfl-extension-school/advanced-exploratory-data-analysis-eda-with-python-536fa83c578a